(()=>{
const C=window.SCHEDULE_CONFIG,D=window.SCHEDULE_DRAW,$=s=>document.querySelector(s),els={title:$('#title'),weekLabel:$('#weekLabel'),channel:$('#channel'),theme:$('#theme'),fontStyle:$('#fontStyle'),decoration:$('#decoration'),avatarFile:$('#avatarFile'),avatarPreview:$('#avatarPreview'),days:$('#days'),canvas:$('#scheduleCanvas'),status:$('#status')};
const GAME_OPTIONS=Array.isArray(window.SCHEDULE_GAMES)?window.SCHEDULE_GAMES:[];
let avatarData='',saveTimer,renderToken=0;
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function gameOptions(selected=''){const options=['<option value="">Seleziona attività</option>'];for(const game of GAME_OPTIONS){const name=esc(game.name);options.push(`<option value="${name}" ${game.name===selected?'selected':''}>${name}</option>`)}return options.join('')}
function gameByName(name){return GAME_OPTIONS.find(game=>game.name===name)||null}
function rows(){C.days.forEach(day=>{const preset=C.defaults[day.key]?.activity||'';const el=document.createElement('div');el.className='day-row';el.innerHTML=`<input class="day-toggle" type="checkbox" id="${day.key}-enabled" aria-label="Attiva ${day.label}"><select class="activity-select" id="${day.key}-activity">${gameOptions(preset)}</select><input type="time" id="${day.key}-time">`;els.days.appendChild(el)})}
function currentWeek(){const now=new Date,day=now.getDay()||7,mon=new Date(now);mon.setHours(12,0,0,0);mon.setDate(now.getDate()-day+1);const sun=new Date(mon);sun.setDate(mon.getDate()+6);const m=d=>d.toLocaleDateString('en-US',{month:'short'}).toUpperCase();els.weekLabel.value=mon.getMonth()===sun.getMonth()?`${String(mon.getDate()).padStart(2,'0')} / ${String(sun.getDate()).padStart(2,'0')} ${m(sun)}`:`${String(mon.getDate()).padStart(2,'0')} ${m(mon)} / ${String(sun.getDate()).padStart(2,'0')} ${m(sun)}`}
function defaults(){els.title.value='STREAM SCHEDULE';currentWeek();els.channel.value='@yourchannel';els.theme.value='lilac';els.fontStyle.value='dynapuff';els.decoration.value='dreamy';avatarData='';preview();C.days.forEach(d=>{const v=C.defaults[d.key];$(`#${d.key}-enabled`).checked=v.enabled;$(`#${d.key}-activity`).value=v.activity;$(`#${d.key}-time`).value=v.time})}
function state(){const schedule={};C.days.forEach(d=>{const activity=$(`#${d.key}-activity`).value,game=gameByName(activity);schedule[d.key]={enabled:$(`#${d.key}-enabled`).checked,activity,time:$(`#${d.key}-time`).value,cover:game?.cover||''}});return{title:els.title.value.trim(),weekLabel:els.weekLabel.value.trim(),channel:els.channel.value.trim(),theme:els.theme.value,fontStyle:els.fontStyle.value,decoration:els.decoration.value,schedule}}
function apply(s){els.title.value=s.title??'STREAM SCHEDULE';els.weekLabel.value=s.weekLabel??'';els.channel.value=s.channel??'@yourchannel';els.theme.value=s.theme??'lilac';els.fontStyle.value=s.fontStyle??'dynapuff';els.decoration.value=s.decoration??'dreamy';avatarData=s.avatarData??'';preview();C.days.forEach(d=>{const v=s.schedule?.[d.key]??C.defaults[d.key];$(`#${d.key}-enabled`).checked=!!v.enabled;$(`#${d.key}-activity`).value=GAME_OPTIONS.some(g=>g.name===v.activity)?v.activity:'';$(`#${d.key}-time`).value=v.time??''})}
function persist(show=false){try{const s=state();s.avatarData=avatarData;localStorage.setItem(C.storageKey,JSON.stringify(s));if(show)flash('✓ salvato nel browser')}catch{flash('salvataggio locale non disponibile')}}
function restore(){try{const raw=localStorage.getItem(C.storageKey);raw?apply(JSON.parse(raw)):defaults()}catch{defaults()}}
function preview(){if(avatarData){els.avatarPreview.src=avatarData;return}const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#8aa4c7"/><stop offset="1" stop-color="#34445c"/></linearGradient></defs><rect width="96" height="96" rx="28" fill="url(#g)"/><text x="48" y="59" text-anchor="middle" font-size="26" font-family="Arial" font-weight="900" fill="white">SM</text></svg>`;els.avatarPreview.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function flash(msg){const old=els.status.textContent;els.status.textContent=msg;clearTimeout(els.status._t);els.status._t=setTimeout(()=>els.status.textContent=old,1700)}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(false),250)}
async function render(){const token=++renderToken;try{await document.fonts.ready}catch{}if(token!==renderToken)return;await D.renderSchedule({canvas:els.canvas,state:state(),avatarData,tokenValid:()=>token===renderToken})}
async function download(){await render();const a=document.createElement('a'),safe=(els.weekLabel.value||'week').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();a.download=`schedule-maker-${safe}.png`;a.href=els.canvas.toDataURL('image/png');a.click();flash('✓ png creato')}
rows();restore();render();document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('input',()=>{render();scheduleSave()});el.addEventListener('change',()=>{render();scheduleSave()})});els.avatarFile.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{avatarData=String(r.result||'');preview();render();scheduleSave()};r.readAsDataURL(f)});$('#currentWeekBtn').addEventListener('click',()=>{currentWeek();render();scheduleSave()});$('#saveBtn').addEventListener('click',()=>persist(true));$('#downloadBtn').addEventListener('click',download);$('#resetBtn').addEventListener('click',()=>{if(!confirm('Ripristinare il programma di esempio?'))return;localStorage.removeItem(C.storageKey);defaults();persist();render();flash('reset completato')});
})();
